#generate code for compose.yamlversion: '3.8'
services:
  db:
    image: 6362437164/myname:dbimage
    ports:
     - "33306:3306"
    deploy:
      replicas: 1
    volumes:
     - db_data:/var/lib/mysql 
  auth_service:
     image: 6362437164/myname:authimage
     ports:
      - "5001:5001" 
     deploy:
        replicas: 1
     depends_on:
      - db     
  book_service:
    image: 6362437164/myname:bookimage
    ports:
      - "5002:5002"
    deploy:
        replicas: 1
  borrow_service:
    image: 6362437164/myname:borrowimage
    ports:
      - "5003:5003"
    deploy:
        replicas: 1
app_image:
    image: 6362437164/myname:appimage
    ports:
      - "5000:5000"
    deploy:
        replicas: 1
    depends_on:
      - auth_service
      - book_service
      - borrow_service